### PR TITLE
Comply with PDS skeleton

### PR DESCRIPTION
**Pull request by jakejohns**
https://github.com/php-pds/skeleton

### CODE REVIEW

**Comment by pmjones** [comment]
Nice. I've had this on my mind for a while now.

**Comment by pmjones** [comment]
@jakejohns Can you add a line to the composer manifest for "pds/skeleton" ~1.0 ? I'll merge after that. Then probably a stable release. :-)

**Comment by jakejohns** [comment]
Right on, I had held off cuz there wasnt a non-beta. Will do now

**Comment by jakejohns** [comment]
Should be done. You want that as a *dev* dependency, right?

**Comment by pmjones** [comment]
Yup, looks good. (Need to attend to Travis soon.)

**Pull request merged**
